### ISSUE TITLE
Normal nether portals do not work

### ISSUE THREAD

**Issue by ghost** [McCraftaholics/Bukkit-WarpPortals#41]
I am running Spigot 1.8.8, and I have WarpPortals-5.6.5-SNAPSHOT.jar installed. All of my Warp portals work fine, but portals that players create do not transport them to the Nether. This is my config: 

```
# Mess with these all you want!
portals:
  general:
    allowNormalPortals: true
    textColor: c
  create: 
    maxSize: 1000 
  permission:
    alertUser: true #
    checkIndividualPortalPermissions: false 
  teleport: 
    message: Wooooooosh! 
    messageColor: d 
  reporting:
    allowAnalytics: true 
```

As you can see, I have allowNormalPortals to `true`. What's going wrong?
